# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Docker Advent
tagline:          'Small thoughts about docker in advent'
description:      'Made by <a href="https://twitter.com/abtris" target="_blank">@abtris</a>.'
url:              http://www.dockeradvent.com
baseurl:          /

author:
  name:           'Ladislav Prskavec'
  url:            https://twitter.com/abtris

paginate:         8

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/abtris/dockeradvent.com
